### ISSUE TITLE
移动距离和页面缩放重新计算问题

### ISSUE THREAD

**Issue by yang123guo** [tinper-bee/bee-affix#1]
### 本地环境

win 10   chorome 60+  version v-1.0.0

### 问题描述
1、页面缩放以后 固定位置重新计算有误。
2、固定跟随有一定跟随距离限制，不会一直跟随到滚动条滚到底部。

如图：
![default](https://user-images.githubusercontent.com/17383237/32263249-e2da3ef2-bf13-11e7-800c-b5bf64435ebe.gif)

**Comment by HuYuee** [comment]
问题已解决，请更新到1.0.1即可
